services:
  gustopro-website:
    build: .
    container_name: gustopro-website
    restart: unless-stopped
    ports:
      - "3010:80"
    labels:
      - "project=gustopro-website"
    networks:
      - default
      - npm-net

networks:
  npm-net:
    external: true
